server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.119.173.233:3306/rhb_cms_admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: "rh@2023"
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml